[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -n auto
    --browser chromium
    --browser firefox
    --browser webkit
    --tracing retain-on-failure
    --screenshot only-on-failure
